version: "3"
services:
  todotests:
    depends_on:
      - "todofront"
      - "todoback"
    image: todotests
    environment:
      - FRONT_HOST=todofront
  todofront:
    ports:
      - 3000:3000
    image: todofrontend
    depends_on:
    - "todoback"
    environment:
    - REACT_APP_API_HOST=todoback
  todoback:
    ports:
      - 3001:3001
    image: todobackend
